server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: knowledge-ingestion-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:donpetre}
    username: ${DB_USERNAME:don}
    password: ${DB_PASSWORD:don_pass}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080}

  # Task Scheduling
  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,scheduledtasks
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always

# Logging Configuration
logging:
  level:
    com.openrangelabs.donpetre.ingestion: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.r2dbc: ${R2DBC_LOG_LEVEL:INFO}
    org.springframework.scheduling: ${SCHEDULING_LOG_LEVEL:DEBUG}
    org.kohsuke.github: ${GITHUB_LOG_LEVEL:INFO}
    org.gitlab4j: ${GITLAB_LOG_LEVEL:INFO}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

# Custom Application Configuration
ingestion:
  # Default connector settings
  connectors:
    github:
      enabled: false
      rate-limit:
        requests-per-hour: 5000
        respect-limits: true
      polling-interval-minutes: 30
      batch-size: 100

    gitlab:
      enabled: false
      rate-limit:
        requests-per-minute: 300
        respect-limits: true
      polling-interval-minutes: 15
      batch-size: 100

    jira:
      enabled: false
      rate-limit:
        requests-per-minute: 100
        respect-limits: true
      polling-interval-minutes: 10
      batch-size: 50

    slack:
      enabled: false
      rate-limit:
        requests-per-minute: 50
        respect-limits: true
      polling-interval-minutes: 5
      batch-size: 100

  # Job management
  jobs:
    cleanup:
      enabled: true
      retention-days: 30
      schedule: "0 2 * * *" # Daily at 2 AM

    credential-check:
      enabled: true
      expiration-warning-days: 7
      schedule: "0 8 * * MON" # Monday at 8 AM

    max-concurrent-jobs: 5
    job-timeout-minutes: 60

  # Encryption settings
  encryption:
    algorithm: AES
    key-length: 256

# Security Configuration
security:
  jwt:
    resource-id: knowledge-ingestion-service

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.openrangelabs.donpetre.ingestion: DEBUG
    org.springframework.scheduling: DEBUG

ingestion:
  jobs:
    cleanup:
      retention-days: 7 # Shorter retention in dev

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.openrangelabs.donpetre.ingestion: INFO
    org.springframework.scheduling: WARN

ingestion:
  jobs:
    max-concurrent-jobs: 10
    job-timeout-minutes: 120

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker

  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/donpetre
    username: don
    password: don_pass